[configs]
number_of_process = 1
duration = 2

[[requests]]
name = "get_request"
url = "http://localhost:8080/get"
method = "GET"
save_result = true

[[requests]]
name = "post_request"
url = "http://localhost:8080/post"
data = '{"name": "{{ get_request.name }}"}'
method = "POST"
