[configs]
number_of_concurrent_flows = 10
duration = 60

[[api]]
name = "user_api"
base_url = "http://192.168.1.107:8080"

[[api]]
name = "any_api"
base_url = "http://192.168.1.105:1010"

[[request]]
name = "get_user"
url = "{{ user_api.base_url }}/users/1"
method = "GET"
save_result = true

[[request]]
name = "create_new_user"
url = "{{  user_api.base_url }}/users/"
method = "POST"
[request.data]
firstname = "{{ get_user.firstname }} teste"
lastname = "{{ get_user.Lastname }} teste"
status = "{{ get_user.status }} teste"
