version: 2.1

orbs:
  poetry: australianunions/poetry@0.1.26
  
workflows:
  bloodaxe-ci:
    jobs:
      - install
      - run

jobs:
  install:
    executor: poetry/default
    steps:
      - poetry/install
      - run: echo "the CLI is now installed"
  run:
    executor: poetry/default
    steps:
      - run:
          command: make lint
          name: lint
      - run:
          command: make test
          name: Test
