--- 
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/python:3.8"
    steps: 
      - checkout
      - 
        run: "sudo chown -R circleci:circleci /usr/local/bin"
      - 
        run: "sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages"
      - 
        restore_cache: 
          key: "deps9-{{ .Branch }}-{{ checksum \"Poetry.lock\" }}"
      - 
        run: 
          command: |
              sudo pip install poetry
              poetry install
      - 
        save_cache: 
          key: "deps9-{{ .Branch }}-{{ checksum \"Poetry.lock\" }}"
          paths: 
            - venv
      - 
        run: 
          command: "make lint\n"
      - 
        run: 
          command: "make test\n"
      - 
        store_test_results: 
          path: test-results
      - 
        store_artifacts: 
          destination: tr1
          path: test-results
version: 2.1
